version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=digital-paani
    volumes:
      - mongodb-data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 3000:3000  
    environment:
      - PORT=3000
      - DATABASE_URI=mongodb://mongodb:27017/digital-paani  
    depends_on:
      - mongodb  


volumes:
  mongodb-data: